### ISSUE TITLE
Add a link about MESG Marketplace Backend

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/marketplace.mesg.com#11]
The backend of the marketplace is made with MESG, I think that would be great to have in a footer something like `build with 🖤with MESG by MESG` or something like that with the sources of the backend.

**Comment by NicolasMahe** [comment]
Good idea but let's not use the "build with love" dumb sentence.

I recommend: "Built using MESG" or if we have a tuto or any explanation: "Built using MESG. See how we did it."
