### ISSUE TITLE
Production and test version

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/marketplace.mesg.com#19]
It will be really nice to have both a production and a test / dev version of the website, like:
Production: http://marketplace.mesg.com
Test / Dev: http://dev.marketplace.mesg.com

**Comment by antho1404** [comment]
The explorer is now connected to an engine, so this doesn't depend on the explorer itself.
I agree we should have an explorer for every single network
- testnet.explorer.mesg.com
- mainnet.explorer.mesg.com
- Why not even something like local.explorer.mesg.com that will connect to your local node

**Comment by NicolasMahe** [comment]
the testnet explorer is available at http://explorer.testnet.mesg.com/
