### ISSUE TITLE
Service api should display if field is repeated

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/marketplace.mesg.com#28]
Currently, the tab API of the marketplace doesn't show that a input or output is repeated.

**Comment by antho1404** [comment]
It now shows if it's a list

eg:

Key | Required | List | Type | Description
-- | -- | -- | -- | --
method | true | false | String |  
privateKey | true | false | String |  
inputs | true | true | Any | 

example: https://marketplace.mesg.com/service/7qr6wyBowJQf9PYoZFURW9ZEf8wkgDBR7Yh3MeGuPr41/tasks
