### ISSUE TITLE
Explorer improvement

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/marketplace.mesg.com#48]
Let's keep a track of all the most important improvement we need on the explorer.

- [ ] Add account balances
We need to have dedicated page and a block on the side of the page that displays the balances of any account. The users' accounts but also the upcoming resources' account. Every time the explorer displays an address, it adds a link to the associated account's page.

- [ ] Transaction WebSocket
The current implementation of the transaction WebSocket broke when @antho1404 start the erc20 monitoring process. This process creates 2 transactions for every erc20 transfers on Ethereum. It didn't break the network but definitely broke the explorer. The explorer couldn't load the transaction fast enough and make the explorer's service to stop working.
I would suggest to remove the WebSocket and to remove the list of transaction page until we have a proper fix.
The best will be to save in a very fast and queryable database all the transactions and make the explorer query it with a pagination system.

- [ ] Pagination
Any api that returns a list should have a pagination mechanism. Again, because of the erc20 monitoring process, the explorer cannot load the whole list of execution in most cases. We need to take a look at the cosmos's http handler to see if they already have a built-in pagination system in place.

**Comment by antho1404** [comment]
I would like to add also
- [ ] account generation in the tools

**Comment by NicolasMahe** [comment]
related to https://github.com/orgs/mesg-foundation/projects/25#card-34522938
